# Static Qt and MinGW toolchain, matching the mybench Windows build.
FROM fedora:44 AS qt-src

RUN dnf install -y --setopt=install_weak_deps=False \
        mingw64-gcc mingw64-gcc-c++ mingw64-winpthreads-static \
        cmake ninja-build perl python3 patch xz which findutils \
        qt6-qtbase-devel \
    && dnf clean all

ARG QT_VERSION=6.11.1
ARG QT_URL=https://download.qt.io/official_releases/qt/6.11/${QT_VERSION}/submodules

WORKDIR /src
RUN curl -fsSL -o qtbase.tar.xz "${QT_URL}/qtbase-everywhere-src-${QT_VERSION}.tar.xz" \
    && curl -fsSL -o qtsvg.tar.xz "${QT_URL}/qtsvg-everywhere-src-${QT_VERSION}.tar.xz" \
    && tar xf qtbase.tar.xz && tar xf qtsvg.tar.xz && rm -f ./*.tar.xz

FROM qt-src AS qt-static
ARG QT_VERSION=6.11.1

RUN cd qtbase-everywhere-src-${QT_VERSION} \
    && ./configure -static -release -opensource -confirm-license \
        -qt-host-path /usr \
        -prefix /opt/qt6-win-static \
        -qt-zlib -qt-libpng -qt-freetype -qt-harfbuzz -qt-pcre \
        -no-icu -no-dbus -opengl desktop \
        -nomake examples -nomake tests \
        -- -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake \
    && cmake --build . --parallel \
    && cmake --install . \
    && cd /src && rm -rf qtbase-everywhere-src-${QT_VERSION}

RUN cd qtsvg-everywhere-src-${QT_VERSION} \
    && cmake -S . -B build -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE=/opt/qt6-win-static/lib/cmake/Qt6/qt.toolchain.cmake \
        -DQT_HOST_PATH=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/qt6-win-static \
    && cmake --build build --parallel \
    && cmake --install build \
    && cd /src && rm -rf qtsvg-everywhere-src-${QT_VERSION}

FROM qt-static AS windows-build
USER root
RUN dnf install -y --setopt=install_weak_deps=False git gcc-c++ unzip mingw64-openssl-static mingw64-zlib-static \
    && dnf clean all
ARG CPPWINRT_VERSION=2.0.250303.1
ARG SDK_VERSION=10.0.26100.3916
RUN git clone --depth 1 --branch ${CPPWINRT_VERSION} https://github.com/microsoft/cppwinrt.git /src/cppwinrt \
    && cmake -S /src/cppwinrt -B /src/cppwinrt/build -G Ninja \
        -DCPPWINRT_BUILD_VERSION=${CPPWINRT_VERSION} -DCMAKE_BUILD_TYPE=Release \
    && cmake --build /src/cppwinrt/build --parallel 4 \
    && curl -fsSL -o /src/contracts.zip https://api.nuget.org/v3-flatcontainer/microsoft.windows.sdk.contracts/${SDK_VERSION}/microsoft.windows.sdk.contracts.${SDK_VERSION}.nupkg \
    && unzip -q /src/contracts.zip -d /src/contracts \
    && /src/cppwinrt/build/cppwinrt -input /src/contracts/ref/netstandard2.0 -output /opt/cppwinrt \
    && rm -rf /src/cppwinrt /src/contracts /src/contracts.zip
WORKDIR /work
